name: flutter_code_organizer
description: Help organize your flutter code
version: 0.0.1+8

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  args: ^2.5.0
  colorize: ^3.0.0
  meta: ^1.15.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

flutter_code_organizer:
